/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiGraphStatsRouteImport } from './routes/api/graph/stats'
import { Route as ApiGraphSimilarIncidentsRouteImport } from './routes/api/graph/similar-incidents'
import { Route as ApiGraphServiceMapRouteImport } from './routes/api/graph/service-map'
import { Route as ApiGraphSeedRouteImport } from './routes/api/graph/seed'
import { Route as ApiGraphRootCauseRouteImport } from './routes/api/graph/root-cause'
import { Route as ApiGraphBlastRadiusRouteImport } from './routes/api/graph/blast-radius'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGraphStatsRoute = ApiGraphStatsRouteImport.update({
  id: '/api/graph/stats',
  path: '/api/graph/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGraphSimilarIncidentsRoute =
  ApiGraphSimilarIncidentsRouteImport.update({
    id: '/api/graph/similar-incidents',
    path: '/api/graph/similar-incidents',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGraphServiceMapRoute = ApiGraphServiceMapRouteImport.update({
  id: '/api/graph/service-map',
  path: '/api/graph/service-map',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGraphSeedRoute = ApiGraphSeedRouteImport.update({
  id: '/api/graph/seed',
  path: '/api/graph/seed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGraphRootCauseRoute = ApiGraphRootCauseRouteImport.update({
  id: '/api/graph/root-cause',
  path: '/api/graph/root-cause',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGraphBlastRadiusRoute = ApiGraphBlastRadiusRouteImport.update({
  id: '/api/graph/blast-radius',
  path: '/api/graph/blast-radius',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/graph/blast-radius': typeof ApiGraphBlastRadiusRoute
  '/api/graph/root-cause': typeof ApiGraphRootCauseRoute
  '/api/graph/seed': typeof ApiGraphSeedRoute
  '/api/graph/service-map': typeof ApiGraphServiceMapRoute
  '/api/graph/similar-incidents': typeof ApiGraphSimilarIncidentsRoute
  '/api/graph/stats': typeof ApiGraphStatsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/graph/blast-radius': typeof ApiGraphBlastRadiusRoute
  '/api/graph/root-cause': typeof ApiGraphRootCauseRoute
  '/api/graph/seed': typeof ApiGraphSeedRoute
  '/api/graph/service-map': typeof ApiGraphServiceMapRoute
  '/api/graph/similar-incidents': typeof ApiGraphSimilarIncidentsRoute
  '/api/graph/stats': typeof ApiGraphStatsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/graph/blast-radius': typeof ApiGraphBlastRadiusRoute
  '/api/graph/root-cause': typeof ApiGraphRootCauseRoute
  '/api/graph/seed': typeof ApiGraphSeedRoute
  '/api/graph/service-map': typeof ApiGraphServiceMapRoute
  '/api/graph/similar-incidents': typeof ApiGraphSimilarIncidentsRoute
  '/api/graph/stats': typeof ApiGraphStatsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/chat'
    | '/api/graph/blast-radius'
    | '/api/graph/root-cause'
    | '/api/graph/seed'
    | '/api/graph/service-map'
    | '/api/graph/similar-incidents'
    | '/api/graph/stats'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/chat'
    | '/api/graph/blast-radius'
    | '/api/graph/root-cause'
    | '/api/graph/seed'
    | '/api/graph/service-map'
    | '/api/graph/similar-incidents'
    | '/api/graph/stats'
  id:
    | '__root__'
    | '/'
    | '/api/chat'
    | '/api/graph/blast-radius'
    | '/api/graph/root-cause'
    | '/api/graph/seed'
    | '/api/graph/service-map'
    | '/api/graph/similar-incidents'
    | '/api/graph/stats'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiGraphBlastRadiusRoute: typeof ApiGraphBlastRadiusRoute
  ApiGraphRootCauseRoute: typeof ApiGraphRootCauseRoute
  ApiGraphSeedRoute: typeof ApiGraphSeedRoute
  ApiGraphServiceMapRoute: typeof ApiGraphServiceMapRoute
  ApiGraphSimilarIncidentsRoute: typeof ApiGraphSimilarIncidentsRoute
  ApiGraphStatsRoute: typeof ApiGraphStatsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/graph/stats': {
      id: '/api/graph/stats'
      path: '/api/graph/stats'
      fullPath: '/api/graph/stats'
      preLoaderRoute: typeof ApiGraphStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/graph/similar-incidents': {
      id: '/api/graph/similar-incidents'
      path: '/api/graph/similar-incidents'
      fullPath: '/api/graph/similar-incidents'
      preLoaderRoute: typeof ApiGraphSimilarIncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/graph/service-map': {
      id: '/api/graph/service-map'
      path: '/api/graph/service-map'
      fullPath: '/api/graph/service-map'
      preLoaderRoute: typeof ApiGraphServiceMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/graph/seed': {
      id: '/api/graph/seed'
      path: '/api/graph/seed'
      fullPath: '/api/graph/seed'
      preLoaderRoute: typeof ApiGraphSeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/graph/root-cause': {
      id: '/api/graph/root-cause'
      path: '/api/graph/root-cause'
      fullPath: '/api/graph/root-cause'
      preLoaderRoute: typeof ApiGraphRootCauseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/graph/blast-radius': {
      id: '/api/graph/blast-radius'
      path: '/api/graph/blast-radius'
      fullPath: '/api/graph/blast-radius'
      preLoaderRoute: typeof ApiGraphBlastRadiusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiChatRoute: ApiChatRoute,
  ApiGraphBlastRadiusRoute: ApiGraphBlastRadiusRoute,
  ApiGraphRootCauseRoute: ApiGraphRootCauseRoute,
  ApiGraphSeedRoute: ApiGraphSeedRoute,
  ApiGraphServiceMapRoute: ApiGraphServiceMapRoute,
  ApiGraphSimilarIncidentsRoute: ApiGraphSimilarIncidentsRoute,
  ApiGraphStatsRoute: ApiGraphStatsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
